import { useState } from "react";
import { Link } from "react-router-dom";
import { TAGS } from "../../shared/tags";
import Reveal from "../../components/marketing/Reveal";
import { IconArrowRight, IconCheck, IconUsers, IconBrain, IconClipboard, IconSignal, IconHandRaised, IconRelease, IconKey, IconPlus } from "../../components/icons";
import shared from "../../styles/marketing.module.css";
import css from "./MentorsPage.module.css";

const chapters = [
  { label:"Find your people", title:"Someone in this room needs what you know.", copy:"Choose the skills you feel comfortable sharing. The queue brings matching questions into focus, so you can spend your energy helping.", action:"Set your skills", status:"Ready to help", Icon:IconBrain },
  { label:"Make the connection", title:"A little context. A much better conversation.", copy:"Read the problem and what the team has already tried. Claim the request when you're ready to head over. They will know who's coming.", action:"I can help", status:"On the way", Icon:IconHandRaised },
  { label:"Build understanding", title:"Don't just fix the bug. Help it make sense.", copy:"Start helping when you reach the table. Work through the blocker together and give the team a way to recognize the problem next time.", action:"Start helping", status:"Working together", Icon:IconUsers },
  { label:"Keep the room moving", title:"One breakthrough leads to the next.", copy:"Resolve the request when the team is unblocked. If you can't continue, release it with its original waiting age so another mentor can step in.", action:"Resolve or release", status:"Back to building", Icon:IconCheck },
];
const examples = [
  { title:"State resets when switching tabs", main:"React", extra:"TypeScript", table:"B4", age:8 },
  { title:"API works locally, fails in production", main:"Backend", extra:"Deployment", table:"A2", age:12 },
  { title:"Query slows down as our data grows", main:"Database", extra:"Backend", table:"C1", age:6 },
  { title:"Modal isn't usable with a keyboard", main:"UI", extra:"JavaScript", table:"D3", age:4 },
  { title:"A merge brought back deleted code", main:"Git", extra:"TypeScript", table:"B1", age:9 },
];
export default function MentorsPage() {
  const [chapter, setChapter] = useState(0);
  const [skills, setSkills] = useState<string[]>(["React", "TypeScript"]);
  const [all, setAll] = useState(false);
  const [available, setAvailable] = useState(true);
  const current = chapters[chapter]!;
  const tier = (item: typeof examples[number]) => skills.includes(item.main) ? 1 : skills.includes(item.extra) ? 2 : 3;
  const sorted = [...examples].sort((a,b) => (all ? 0 : tier(a)-tier(b)) || b.age-a.age);
  return <div className={css.page}>
    <section className={css.hero}>
      <div className={css.heroTop}><span>FOR THE PEOPLE WHO SHOW UP</span><span>THE MENTOR JOURNEY · 01—04</span></div>
      <div className={css.heroGrid}>
        <div className={css.heroCopy}><p className={css.kicker}>FOR MENTORS</p><h1>A little of your time.<br /><span>A lot of possibility.</span></h1><p>You don't need every answer. Just the experience to ask a better question, and the willingness to pull up a chair.</p><Link className={shared.btnPrimary} to="/join">Join as a mentor<IconArrowRight size={18}/></Link></div>
        <div className={css.scene} aria-hidden="true"><span className={css.sceneLabel}>GOOD IDEAS GROW TOGETHER</span><svg viewBox="0 0 480 330" fill="none"><ellipse cx="244" cy="170" rx="170" ry="135" stroke="#d3b8e9" strokeDasharray="5 8"/><path d="M76 256h338M99 255v47m290-47v47" stroke="#00004e" strokeWidth="8" strokeLinecap="round"/><path d="M105 244v-66c0-34 66-34 66 0v66" fill="#9c51e8"/><circle cx="138" cy="121" r="30" fill="#cbb0e7"/><path d="M108 116c0-37 61-39 61 0-17-1-24-11-26-17-8 12-20 17-35 17" fill="#00004e"/><path d="M307 244v-66c0-34 66-34 66 0v66" fill="#9cdd2e"/><circle cx="340" cy="121" r="30" fill="#d8c4ed"/><path d="M310 116c0-38 62-38 62 0-21 0-32-5-40-15-3 8-11 14-22 15" fill="#00004e"/><path d="m157 192 40 37m132-37-39 37" stroke="#00004e" strokeWidth="13" strokeLinecap="round"/><rect x="178" y="181" width="122" height="74" rx="7" fill="#00004e"/><path d="m225 205-12 13 12 13m29-26 12 13-12 13m-11-31-8 36" stroke="#c3ed8e" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><rect x="190" y="37" width="103" height="55" rx="14" fill="#fff" stroke="#d7bde9"/><path d="m224 62 10 10 20-21" stroke="#7334bb" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><path d="m255 92-15 14V92" fill="#fff"/><circle cx="77" cy="96" r="7" fill="#9cdd2e"/><path d="M396 57v24m-12-12h24" stroke="#9c51e8" strokeWidth="4" strokeLinecap="round"/></svg><div className={css.sceneStatus}><span/>{current.status}</div></div>
      </div>
      <div className={css.chapterNav} role="group" aria-label="Explore the mentor journey">{chapters.map((item,i)=><button type="button" key={item.label} aria-pressed={chapter===i} aria-controls="mentor-chapter" onClick={()=>setChapter(i)}><span>0{i+1}</span>{item.label}<IconArrowRight size={16}/></button>)}</div>
      <div id="mentor-chapter" className={css.chapterPanel} aria-live="polite"><div key={chapter} className={css.chapterContent}><current.Icon size={26}/><h2>{current.title}</h2><p>{current.copy}</p><span>{current.action}</span></div></div>
    </section>
    <section className={`${css.section} ${css.intro}`}><Reveal><p className={css.kicker}>WHY WE'RE HERE</p><h2>Behind every breakthrough,<br />there's usually <span>another person.</span></h2></Reveal><Reveal delayMs={100}><p>A hackathon brings a room full of knowledge together. DevSOS helps that knowledge find its way to the teams that need it.</p><p>Set your skills once. See the context before you commit. Spend your time having the conversations that keep people building.</p></Reveal></section>
    <section className={css.motto}><div className={css.section}><p className={css.kicker}>THE MENTOR MINDSET</p><h2>Listen.<span> Connect.</span><br />Build confidence.</h2><p>Leave the team with more than working code.<br />Leave them with a clearer way to think.</p></div></section>
    <section className={css.section}><div className={css.heading}><div><p className={css.kicker}>YOUR WORKSPACE</p><h2>Less coordination.<br />More contribution.</h2></div><p>The small details that help you stay present, from your first question to your last conversation.</p></div><div className={css.cards}>{[{Icon:IconSignal,title:"Room to take a break",body:"Switch to Away for food, rest or judging. Your current request stays with you; you simply stop being counted as free capacity."},{Icon:IconBrain,title:"Skills you actually use",body:"Choose topics you're comfortable with. Honest choices make matching useful, and a request outside your skills is still yours to explore."},{Icon:IconClipboard,title:"The story before the walk",body:"See the problem, attempted fixes, table and waiting time before you claim. Start with context instead of starting from zero."}].map(({Icon,title,body},i)=><Reveal delayMs={i*90} key={title}><article><Icon size={29}/><h3>{title}</h3><p>{body}</p></article></Reveal>)}</div></section>
    <section className={css.matchSection}><div className={css.section}><div className={css.heading}><div><p className={css.kicker}>WHERE YOU CAN MAKE A DIFFERENCE</p><h2>Your skills.<br />Someone's next step.</h2></div><p>Try the matching demo. Select skills and watch the example queue reorder. These choices do not change your event profile.</p></div><div className={css.matchGrid}><div><h3>What do you know?</h3><div className={css.skills} role="group" aria-label="Demo mentor skills">{TAGS.map(tag=><button type="button" key={tag} aria-pressed={skills.includes(tag)} onClick={()=>setSkills(prev=>prev.includes(tag)?prev.filter(x=>x!==tag):[...prev,tag])}>{skills.includes(tag)?<IconCheck size={15}/>:<IconPlus size={15}/>} {tag}</button>)}</div><p className={css.small}>{skills.length ? `${skills.length} skills selected. Main-topic matches come first, then extra-topic matches, then other requests.` : "No skills selected. Requests appear oldest first."}</p><div className={css.availability}><div><strong>{available?"Available":"Away"}</strong><p>{available?"You're counted as free capacity.":"Take your time. Your current assignment stays with you."}</p></div><button type="button" role="switch" aria-checked={available} aria-label="Demo mentor availability" onClick={()=>setAvailable(x=>!x)}><span/></button></div><p className={css.small}>Demo only · Availability doesn't change the skill ranking.</p></div><div className={css.queue}><div className={css.queueHead}><span>EXAMPLE QUEUE</span><div role="group" aria-label="Demo queue order"><button type="button" aria-pressed={!all} onClick={()=>setAll(false)}>For your skills</button><button type="button" aria-pressed={all} onClick={()=>setAll(true)}>All requests</button></div></div><ol aria-live="polite" aria-label="Sorted example requests">{sorted.map(item=><li key={item.title}><div><span className={css.matchLabel}>{all?"By waiting time":tier(item)===1?"Main-topic match":tier(item)===2?"Extra-topic match":"Other request"}</span><span>{item.age}m waiting{item.age>10?" · Long wait":""}</span></div><h4>{item.title}</h4><p>{item.main} · {item.extra}<span>Table {item.table}</span></p></li>)}</ol></div></div></div></section>
    <section className={css.section}><div className={css.heading}><div><p className={css.kicker}>FOUR CLEAR ACTIONS</p><h2>Always know<br />what comes next.</h2></div><Link className={shared.arrowLink} to="/how-it-works">See the complete flow<IconArrowRight size={18}/></Link></div><div className={css.actions}>{[{Icon:IconHandRaised,title:"I can help",text:"Claim when you're ready to head over. Your name appears on the team's card."},{Icon:IconUsers,title:"Start helping",text:"Start at the table. Waiting time becomes time with a mentor."},{Icon:IconCheck,title:"Resolve",text:"The team is unblocked. You or the team can close the request."},{Icon:IconRelease,title:"Release",text:"Hand it back if you can't continue. It keeps its original waiting age."}].map(({Icon,title,text},i)=><article key={title}><div><span>0{i+1}</span><Icon size={23}/></div><h3>{title}</h3><p>{text}</p></article>)}</div><p className={css.notice}>If another mentor claims first, you'll see a clear message and an updated queue. Only one mentor gets the assignment.</p></section>
    <section className={css.closing}><IconKey size={34}/><p className={css.kicker}>BRING YOUR EXPERIENCE. WE'LL HELP YOU FIND YOUR PEOPLE.</p><h2>Be someone's<br /><span>“now I get it.”</span></h2><p>Ask your organizer for the event code and mentor invitation.<br />Both go into the same join screen.</p><Link className={shared.btnPrimary} to="/join">Join as a mentor<IconArrowRight size={19}/></Link></section>
  </div>;
}
