import { useState } from "react";
import { Link } from "react-router-dom";
import Reveal from "../../components/marketing/Reveal";
import { IconChart, IconClock, IconWrench, IconPower, IconArrowRight, IconCheck, IconKey, IconShield, IconWifiOff, IconUsers, IconClipboard } from "../../components/icons";
import shared from "../../styles/marketing.module.css";
import css from "./GuidePages.module.css";

const phases = [
  { title:"Before doors open", subtitle:"Set the room up for a good start.", items:["Create the event and display its code where everyone can see it.","Share the mentor invitation with mentors only.","Ask mentors to choose their skills when they arrive.","Assign someone to watch the dashboard during each shift."] },
  { title:"During the event", subtitle:"Keep an eye on the people still waiting.", items:["Keep the dashboard open on a spare screen.","Check the oldest waiting requests first.","Release claims when the assigned mentor cannot continue.","Cancel duplicates and abandoned requests."] },
  { title:"At the end", subtitle:"Finish the conversations, then close the room.", items:["Resolve or cancel remaining requests before closing the event.","Note the busiest topics to plan mentor coverage next time.","Close the event when you're ready to stop new requests."] },
];
const preview = [
  { label:"Waiting", value:3, title:"Teams that need a hand", rows:["B4 · Backend · 14m waiting", "C2 · Database · 8m waiting", "A1 · Git · 4m waiting"], note:"Requests past ten minutes are flagged so you can bring help where it's needed." },
  { label:"Claimed", value:2, title:"A mentor is on the way", rows:["D7 · UI · Claimed by Sam", "B2 · React · Claimed by Alex"], note:"If a mentor gets pulled away, release the claim so another mentor can pick it up." },
  { label:"In progress", value:2, title:"Conversations in progress", rows:["A4 · TypeScript · With Jordan", "C5 · Deployment · With Casey"], note:"The team and mentor are working together. The request stays visible until it is closed." },
  { label:"Resolved", value:12, title:"Back to building", rows:["B3 · Backend · Resolved", "A8 · React · Resolved", "C7 · Git · Resolved"], note:"Showing three of twelve example resolutions. Closed requests help you understand how the event went." },
  { label:"Cancelled", value:1, title:"No longer needs help", rows:["D1 · JavaScript · Cancelled by team"], note:"Teams can cancel when they solve a problem themselves. It keeps the queue accurate." },
];
export default function OrganizersPage() {
  const [status,setStatus] = useState(0);
  const [phase,setPhase] = useState(0);
  const [checked,setChecked] = useState<string[]>([]);
  const total = phases.reduce((sum,item)=>sum+item.items.length,0);
  const current=preview[status]!;
  return <div className={css.page}>
    <section className={css.organizerHero}><div className={css.heroGrid}><div><p className={css.kicker}>FOR THE PEOPLE BEHIND THE EVENT</p><h1>A room full of ideas.<br /><span>A clear view of it all.</span></h1><p className={css.lede}>Give every team a way to ask. Give every mentor a place to start. Keep the whole help desk moving from one dashboard.</p><div className={shared.ctaRow}><Link className={shared.btnPrimary} to="/join">Open your event<IconArrowRight size={18}/></Link><a className={shared.btnGhost} href="#run-sheet">Plan your event<IconArrowRight size={18}/></a></div><p className={css.micro}><IconCheck size={15}/> One event code. Clear roles. Less coordination.</p></div><div className={css.dashboard}><div className={css.dashboardTop}><span><IconChart size={18}/> THE ROOM AT A GLANCE</span><small>INTERACTIVE EXAMPLE</small></div><div className={css.statusGrid} role="group" aria-label="Preview requests by status">{preview.map((item,i)=><button type="button" key={item.label} aria-pressed={status===i} aria-controls="organizer-preview" onClick={()=>setStatus(i)}><strong>{item.value}</strong><span>{item.label}</span></button>)}</div><div id="organizer-preview" aria-live="polite" className={css.previewContent}><div key={status} className={css.swap}><h2>{current.title}</h2><ul>{current.rows.map(row=><li key={row}><IconClock size={15}/>{row}</li>)}</ul><p>{current.note}</p></div></div><div className={css.dashboardFoot}><IconUsers size={16}/> Example data · Select a status to explore</div></div></div></section>
    <section className={css.section}><div className={css.heading}><div><p className={css.kicker}>LESS GUESSWORK</p><h2>Know where to look.<br />Know when to step in.</h2></div><p>A good help desk makes waiting visible. You can spot a queue building up before teams lose their momentum.</p></div><div className={css.featureGrid}>{[{Icon:IconChart,title:"See the whole picture",body:"Waiting, claimed, in progress, resolved and cancelled. Counts update as requests move through the room."},{Icon:IconClock,title:"Notice the long waits",body:"Check the oldest requests first. Anything past ten minutes is flagged, giving you a clear place to focus."},{Icon:IconWrench,title:"Keep things moving",body:"Release a stuck claim, resolve a finished request or cancel a duplicate. Organizers can act on active requests."},{Icon:IconPower,title:"Close with clarity",body:"Closing stops new requests and makes the queue read-only. Everyone sees that the event has ended."}].map(({Icon,title,body},i)=><Reveal key={title} delayMs={i*75}><article><Icon size={25}/><h3>{title}</h3><p>{body}</p></article></Reveal>)}</div></section>
    <section className={css.runSection} id="run-sheet"><div className={css.section}><div className={css.heading}><div><p className={css.kicker}>YOUR EVENT RUN SHEET</p><h2>A little preparation.<br />A much calmer room.</h2></div><p>A practical checklist for you or your volunteers. Check items as you go; this planning list resets when you leave the page.</p></div><div className={css.runGrid}><div><div className={css.phaseButtons} role="group" aria-label="Event planning phase">{phases.map((item,i)=><button type="button" key={item.title} aria-pressed={phase===i} aria-controls="phase-checklist" onClick={()=>setPhase(i)}><span>0{i+1}</span>{item.title}<IconArrowRight size={17}/></button>)}</div><div className={css.progressCard}><IconClipboard size={24}/><strong>{checked.length}<span> / {total} tasks complete</span></strong><progress value={checked.length} max={total} aria-label="Event planning completion"/><button type="button" disabled={!checked.length} onClick={()=>setChecked([])}>Reset checklist</button></div></div><div className={css.checkPanel} id="phase-checklist"><h3>{phases[phase]!.subtitle}</h3><ul>{phases[phase]!.items.map((item,i)=>{const id=`${phase}-${i}`;return <li key={id}><label><input type="checkbox" checked={checked.includes(id)} onChange={()=>setChecked(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id])}/><span>{item}</span></label></li>;})}</ul><p role="status" className={css.completion}>{checked.length===total?"You're through the run sheet. Ready for a well-supported event.":`${checked.length} of ${total} planning tasks complete.`}</p></div></div></div></section>
    <section className={css.section}><div className={css.heading}><div><p className={css.kicker}>THE FOUNDATIONS</p><h2>Simple to join.<br />Clear about access.</h2></div></div><div className={css.foundationGrid}>{[{Icon:IconKey,title:"The code opens the door",body:"Share the event code with the room. Give the separate mentor invitation only to mentors. An invitation determines access when someone joins."},{Icon:IconShield,title:"Context stays with the right people",body:"Full request details go to the team, the mentor helping them and the organizers. No email account or password is needed to join."},{Icon:IconWifiOff,title:"Connection changes stay visible",body:"When live updates drop, screens refresh every five seconds and show a notice. Existing information stays on screen, marked as stale."}].map(({Icon,title,body})=><article key={title}><Icon size={26}/><h3>{title}</h3><p>{body}</p></article>)}</div><aside className={css.tip}><IconUsers size={24}/><div><strong>Give the help desk a home.</strong><p>Keep the dashboard near your mentor table. A visible waiting count helps volunteers notice where another pair of hands could make a difference.</p></div></aside></section>
    <section className={css.closing}><p className={css.kicker}>MAKE SPACE FOR EVERY QUESTION</p><h2>Your event. Your people.<br /><span>A better way to help.</span></h2><div className={shared.ctaRow}><Link className={shared.btnPrimary} to="/join">Open your event<IconArrowRight size={18}/></Link><Link className={css.lightLink} to="/faq">Explore the FAQ<IconArrowRight size={18}/></Link></div></section>
  </div>;
}
